#!/usr/bin/env bash

#gets and returns the ask price from bittrex
function getAsk(){
	curl -s https://bittrex.com/api/v1/public/getticker?market=BTC-SUPER |jsawk 'return this.result.Ask'
}

#gets and returns the last price from bitrex
function getLast(){
	curl -s https://bittrex.com/api/v1/public/getticker?market=BTC-SUPER |jsawk 'return this.result.Last'
}

#gets and returns the last Bid from bittrex
function getBid(){
    curl -s https://bittrex.com/api/v1/public/getticker?market=BTC-SUPER |jsawk 'return this.result.Bid'
}

# returns the BTC echange
function getBTCUSD(){
	curl -s https://www.bitstamp.net/api/ticker/ | jsawk 'return this.last'
}



